# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "unirennes-poster"
version = "0.3.0"
entrypoint = "src/lib.typ"
authors = ["Augustin Godinot <augustin.godinot@inria.fr"]
license = "Unlicense"
description = "Unofficial Typst template to create posters using Université de Rennes charter"
repository = "https://github.com/grodino/unirennes-poster-typst"
categories = ["poster"]
exclude = [".github", "docs", "scripts", "tests", ".typstignore", "Justfile"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "main.png"
